name: fincalc_pro
description: All-in-one Indian financial calculator with Smart Tax Optimizer.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  pdf: ^3.11.1
  printing: ^5.13.3
  share_plus: ^10.1.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
